
spring:
  datasource:
    name: webcontacts
    url: jdbc:mysql://localhost:3306/webcontacts
    username: root
    password: amananuj
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL8Dialect

  security:
    user:
      name: webcontacts
      password: password
      roles: manager

#spring.datasource.name=webcontactsmlml
#spring.datasource.url=jdbc:mysql://localhost:3306/webcontacts
#spring.datasource.username=root
#spring.datasource.password=amananuj
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.hibernate.ddl-auto=update
#
#spring.security.user.name=webcontacts
#spring.security.user.password=password
#spring.security.user.roles=manager